
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS8 DO;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 SDK_DATA_B0;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8 SDK_DATA_B1;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS8 SDK_DATA_B2;		/* Mapped at index 0x2001, subindex 0x03 */
extern UNS8 SDK_DATA_B3;		/* Mapped at index 0x2001, subindex 0x04 */
extern UNS8 SDK_DATA_B4;		/* Mapped at index 0x2001, subindex 0x05 */
extern UNS8 SDK_DATA_B5;		/* Mapped at index 0x2001, subindex 0x06 */
extern UNS8 SDK_DATA_B6;		/* Mapped at index 0x2001, subindex 0x07 */
extern UNS8 SDK_DATA_B7;		/* Mapped at index 0x2001, subindex 0x08 */
extern UNS8 SDK_RCV_B0;		/* Mapped at index 0x2002, subindex 0x01 */
extern UNS8 SDK_RCV_B1;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS8 SDK_RCV_B2;		/* Mapped at index 0x2002, subindex 0x03 */
extern UNS8 SDK_RCV_B3;		/* Mapped at index 0x2002, subindex 0x04 */
extern UNS8 SDK_RCV_B4;		/* Mapped at index 0x2002, subindex 0x05 */
extern UNS8 SDK_RCV_B5;		/* Mapped at index 0x2002, subindex 0x06 */
extern UNS8 SDK_RCV_B6;		/* Mapped at index 0x2002, subindex 0x07 */
extern UNS8 SDK_RCV_B7;		/* Mapped at index 0x2002, subindex 0x08 */
extern UNS8 DI1;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS8 DI2;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS8 DI3;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS8 DI4;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS8 DI5;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS8 DI6;		/* Mapped at index 0x2014, subindex 0x00*/
extern UNS8 DI7;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS8 DI8;		/* Mapped at index 0x2016, subindex 0x00*/

#endif // TESTMASTER_H
